In [75]:
import pandas as pd
import numpy as np
import os 
import time
from bs4 import BeautifulSoup
import requests
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
#from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.support.ui import WebDriverWait, Select
from selenium.webdriver.support import expected_conditions as EC
import undetected_chromedriver as uc
import concurrent.futures

In [8]:
options = uc.ChromeOptions()# have to use undetected driver to load the expedia page. 
prefs = {"download.default_directory": "/Users/bowiechuang/Downloads/"}
options.add_experimental_option("prefs", prefs) 
options.add_argument("--disable-gpu") #to disabled gpu because expedia page is written by javascript 
#options.headless = True
service = ChromeService("/Users/bowiechuang/Downloads/chromedriver-mac-x64/chromedriver")
driver = uc.Chrome(options = options)
url = "https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&d1=2024-06-28&startDate=2024-06-28&d2=2024-06-30&endDate=2024-06-30&adults=2&rooms=1&lodging=HOTEL&sort=RECOMMENDED&theme=&userIntent=&semdtl=&useRewards=false"
driver.get(url)

WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.CLASS_NAME, "uitk-button.uitk-button-medium.uitk-button-has-text.uitk-button-secondary"))).click()

last_height = driver.execute_script("return document.body.scrollHeight")
while True:
    #scroll down to bottom
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    time.sleep(1)
    new_height = driver.execute_script("return document.body.scrollHeight")
    if new_height== last_height:
        break
    last_height = new_height

time.sleep(2)

content = driver.page_source # retrieve the html file from the driver.get() url 
soup = BeautifulSoup(content, 'html.parser')
# Find the elements containing hotel information
hotel_elements = soup.find_all('div', class_='uitk-card')

# for hotel in hotel_elements:
#     hotel_breakfast_tag = hotel.findAll("div", class_ = "uitk-type-200")
#     print(hotel_breakfast_tag)
    # for tag in hotel_breakfast_tag:
    #     text_value = tag.get_text(strip = True)
    #     print(text_value)

#Initialize an empty list to store the data
data = []

for hotel in hotel_elements:
    # Extract hotel# name
    hotel_name_tag = hotel.find('h3', class_='uitk-heading-5')
    hotel_name = hotel_name_tag.text.strip() if hotel_name_tag else 'No name'
    
    # Extract hotel price
    hotel_price_tag = hotel.find('div', class_='uitk-text-emphasis-theme')
    hotel_price = hotel_price_tag.text.strip() if hotel_price_tag else 'No price'

    #Extract hotel city location
    hotel_city_tag = hotel.find("div", class_ = "uitk-text-spacing-half")
    hotel_city = hotel_city_tag.text.strip() if hotel_city_tag else 'No name'

    hotel_details = [tag.get_text(strip = True) for tag in hotel.findAll("div", class_ = "uitk-type-200")]

    # Append the data to the list
    data.append({
        'hotel_name': hotel_name,
        'hotel_price': hotel_price,
        'hotel_city': hotel_city,
        'detail_1': 'Breakfast included' if hotel_details[0] == 'Breakfast included' else 'N/A',
        'detail_2': 'Pool' if (hotel_details[0] == 'Pool' or hotel_details[1] == 'Pool') else 'N/A',
        # 'detail_3': hotel_details[2] if len(hotel_details) > 2 else 'N/A',
        # 'detail_4': hotel_details[3] if len(hotel_details) > 3 else 'N/A',
        # 'detail_5': hotel_details[4] if len(hotel_details) > 4 else 'N/A'
    })

    print(hotel_details)
# 'detail_1': 'Breakfast Included' if hotel_details[0]  == 'Breakfast Included' else 'N/A',
# 'detail_2': 'Pool' if (hotel_details[0] or hotel_details[1]) == 'Pool' else 'N/A',
# 'detail_3': 'Hot tub' if (hotel_details[0] or hotel_details[1] or hotel_details[2]) == 'Hot tub' else 'N/A'



#     #Extract hotel 
#     hotel_breakfast_tag = hotel.findAll("div", class_ = "uitk-type-200")[0]
#     hotel_breakfast = hotel_breakfast_tag.text.strip() if hotel_city_tag else 'No name'

#     hotel_pool_tag = hotel.findAll("div", class_ = "uitk-type-200")[1]
#     hotel_pool = hotel_pool_tag.text.strip() if hotel_pool_tag else 'No name'

#     hotel_tub_tag = hotel.findAll("div", class_ = "uitk-type-200")[2]
#     hotel_tub = hotel_tub_tag.text.strip() if hotel_city_tag else 'No name'

IndexError: list index out of range

In [3]:
df = pd.DataFrame(data)
df.iloc[0:25]

NameError: name 'data' is not defined

In [21]:
start_date = '2024-09-01'
end_date = '2025-08-31'
date_range_list = pd.date_range(start = start_date, end = end_date)
for i in range(len(date_range_list)):
    try:
        print(f"https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1={date_range_list.date[i]}&startDate={date_range_list.date[i]}&d2={date_range_list.date[i+2]}&endDate={date_range_list.date[i+2]}&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED")
    except:
        break
# def traverse_website(date_list):
#     url = "https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-06-28&startDate=2024-06-28&d2=2024-06-30&endDate=2024-06-30&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED"

https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-01&startDate=2024-09-01&d2=2024-09-03&endDate=2024-09-03&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-02&startDate=2024-09-02&d2=2024-09-04&endDate=2024-09-04&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-03&startDate=2024-09-03&d2=2024-09-05&endDate=2024-09-05&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-04&startDate=2024-09-04&d2=2024-09-06&endDate=2024-09-06&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-05&startDate=2024-09-05&d2=2024-09-07&endDate=2024-09-07&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-06&startDate=2024-09-06&d2=2024-09-08&endDate=2024-09-08&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-07&startDate=2024-09-07&d2=2024-09-09&endDate=2024-09-09&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-08&startDate=2024-09-08&d2=2024-09-10&endDate=2024-09-10&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-09&startDate=2024-09-09&d2=2024-09-11&endDate=2024-09-11&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-10&startDate=2024-09-10&d2=2024-09-12&endDate=2024-09-12&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-11&startDate=2024-09-11&d2=2024-09-13&endDate=2024-09-13&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-12&startDate=2024-09-12&d2=2024-09-14&endDate=2024-09-14&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-13&startDate=2024-09-13&d2=2024-09-15&endDate=2024-09-15&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-14&startDate=2024-09-14&d2=2024-09-16&endDate=2024-09-16&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-15&startDate=2024-09-15&d2=2024-09-17&endDate=2024-09-17&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-16&startDate=2024-09-16&d2=2024-09-18&endDate=2024-09-18&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-17&startDate=2024-09-17&d2=2024-09-19&endDate=2024-09-19&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-18&startDate=2024-09-18&d2=2024-09-20&endDate=2024-09-20&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-19&startDate=2024-09-19&d2=2024-09-21&endDate=2024-09-21&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-20&startDate=2024-09-20&d2=2024-09-22&endDate=2024-09-22&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-21&startDate=2024-09-21&d2=2024-09-23&endDate=2024-09-23&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-22&startDate=2024-09-22&d2=2024-09-24&endDate=2024-09-24&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-23&startDate=2024-09-23&d2=2024-09-25&endDate=2024-09-25&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-24&startDate=2024-09-24&d2=2024-09-26&endDate=2024-09-26&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-25&startDate=2024-09-25&d2=2024-09-27&endDate=2024-09-27&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-26&startDate=2024-09-26&d2=2024-09-28&endDate=2024-09-28&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-27&startDate=2024-09-27&d2=2024-09-29&endDate=2024-09-29&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-28&startDate=2024-09-28&d2=2024-09-30&endDate=2024-09-30&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-29&startDate=2024-09-29&d2=2024-10-01&endDate=2024-10-01&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-09-30&startDate=2024-09-30&d2=2024-10-02&endDate=2024-10-02&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-01&startDate=2024-10-01&d2=2024-10-03&endDate=2024-10-03&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-02&startDate=2024-10-02&d2=2024-10-04&endDate=2024-10-04&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-03&startDate=2024-10-03&d2=2024-10-05&endDate=2024-10-05&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-04&startDate=2024-10-04&d2=2024-10-06&endDate=2024-10-06&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-05&startDate=2024-10-05&d2=2024-10-07&endDate=2024-10-07&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-06&startDate=2024-10-06&d2=2024-10-08&endDate=2024-10-08&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-07&startDate=2024-10-07&d2=2024-10-09&endDate=2024-10-09&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-08&startDate=2024-10-08&d2=2024-10-10&endDate=2024-10-10&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-09&startDate=2024-10-09&d2=2024-10-11&endDate=2024-10-11&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-10&startDate=2024-10-10&d2=2024-10-12&endDate=2024-10-12&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-11&startDate=2024-10-11&d2=2024-10-13&endDate=2024-10-13&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-12&startDate=2024-10-12&d2=2024-10-14&endDate=2024-10-14&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-13&startDate=2024-10-13&d2=2024-10-15&endDate=2024-10-15&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-14&startDate=2024-10-14&d2=2024-10-16&endDate=2024-10-16&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-15&startDate=2024-10-15&d2=2024-10-17&endDate=2024-10-17&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-16&startDate=2024-10-16&d2=2024-10-18&endDate=2024-10-18&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-17&startDate=2024-10-17&d2=2024-10-19&endDate=2024-10-19&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-18&startDate=2024-10-18&d2=2024-10-20&endDate=2024-10-20&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-19&startDate=2024-10-19&d2=2024-10-21&endDate=2024-10-21&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-20&startDate=2024-10-20&d2=2024-10-22&endDate=2024-10-22&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-21&startDate=2024-10-21&d2=2024-10-23&endDate=2024-10-23&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-22&startDate=2024-10-22&d2=2024-10-24&endDate=2024-10-24&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-23&startDate=2024-10-23&d2=2024-10-25&endDate=2024-10-25&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-24&startDate=2024-10-24&d2=2024-10-26&endDate=2024-10-26&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-25&startDate=2024-10-25&d2=2024-10-27&endDate=2024-10-27&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-26&startDate=2024-10-26&d2=2024-10-28&endDate=2024-10-28&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-27&startDate=2024-10-27&d2=2024-10-29&endDate=2024-10-29&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-28&startDate=2024-10-28&d2=2024-10-30&endDate=2024-10-30&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-29&startDate=2024-10-29&d2=2024-10-31&endDate=2024-10-31&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-30&startDate=2024-10-30&d2=2024-11-01&endDate=2024-11-01&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-10-31&startDate=2024-10-31&d2=2024-11-02&endDate=2024-11-02&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-11-01&startDate=2024-11-01&d2=2024-11-03&endDate=2024-11-03&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-11-02&startDate=2024-11-02&d2=2024-11-04&endDate=2024-11-04&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-11-03&startDate=2024-11-03&d2=2024-11-05&endDate=2024-11-05&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-11-04&startDate=2024-11-04&d2=2024-11-06&endDate=2024-11-06&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-11-05&startDate=2024-11-05&d2=2024-11-07&endDate=2024-11-07&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED
https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1=2024-11-06&startDate=2024-11-06&d2=2024-11-08&endDate=2024-11-08&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED

In [67]:
# options = webdriver.ChromeOptions()
# prefs = {"download.default_directory": "/Users/bowiechuang/Downloads/"}
# options.add_experimental_option("prefs", prefs) #stop the UI interface from running
# options.add_argument("--disable-gpu")
# service = ChromeService("/Users/bowiechuang/Downloads/chromedriver-mac-x64/chromedriver")
# driver = webdriver.Chrome(options = options, service = service)
# url = "https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&d1=2024-06-28&startDate=2024-06-28&d2=2024-06-30&endDate=2024-06-30&adults=2&rooms=1&lodging=HOTEL&sort=RECOMMENDED&theme=&userIntent=&semdtl=&useRewards=false"
# driver.get(url)
# time.sleep(5)

# WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.CLASS_NAME, "uitk-button.uitk-button-medium.uitk-button-has-text.uitk-button-secondary"))).click()

# last_height = driver.execute_script("return document.body.scrollHeight")
# while True:
#     #scroll down to bottom
#     driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
#     time.sleep(10)
#     new_height = driver.execute_script("return document.body.scrollHeight")
#     if new_height== last_height:
#         break
#     last_height = new_height

# time.sleep(5)



# content = driver.page_source
# soup = BeautifulSoup(content, 'html.parser')
# # Find the elements containing hotel information
# hotel_elements = soup.find_all('div', class_='uitk-card')

# # Initialize an empty list to store the data
# data = []

# for hotel in hotel_elements:
#     # Extract hotel name
#     hotel_name_tag = hotel.find('h3', class_='uitk-heading-5')
#     hotel_name = hotel_name_tag.text.strip() if hotel_name_tag else 'No name'
    
#     # Extract hotel price
#     hotel_price_tag = hotel.find('div', class_='uitk-text-emphasis-theme')
#     hotel_price = hotel_price_tag.text.strip() if hotel_price_tag else 'No price'

    
#     # Append the data to the list
#     data.append({
#         'hotel_name': hotel_name,
#         'hotel_price': hotel_price,
#     })

#     df = pd.DataFrame(data)
#     df

In [ ]:

#headers = {
 #       'User-Agent': 'Mozilla/5.0 (X11; CrOS x86_64 8172.45.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.64 Safari/537.36',
  #      'Accept-Language': 'en-US, en;q=0.5'
   # }



# hotel_elements = soup.find_all("div", class_="uitk-spacing uitk-spacing-margin-blockstart-three")
# data = []

# for hotel in hotel_elements:
#     hotel_name = hotel.find("h3", class_ = "uitk-heading uitk-heading-5 overflow-wrap uitk-layout-grid-item uitk-layout-grid-item-has-row-start").text.strip() if hotel.find("h3", class_ = "uitk-heading uitk-heading-5 overflow-wrap uitk-layout-grid-item uitk-layout-grid-item-has-row-start") else "No Name"
#     data.append({"hotel_name": hotel_name})
# data

[<div class="uitk-spacing uitk-spacing-margin-blockstart-three"></div>,
 <div class="uitk-spacing uitk-spacing-margin-blockstart-three"><div class="uitk-card uitk-card-roundcorner-all uitk-card-has-border uitk-card-has-primary-theme" data-stid="lodging-card-responsive"><div class="uitk-layout-grid uitk-layout-grid-has-auto-columns uitk-layout-grid-has-columns-by-medium uitk-layout-grid-display-grid" style="--uitk-layoutgrid-auto-columns:minmax(var(--uitk-layoutgrid-egds-size__0x), 1fr);--uitk-layoutgrid-columns-medium:repeat(3, minmax(0, 1fr))"><div class="uitk-layout-flex uitk-layout-flex-block-size-full-size uitk-layout-position uitk-layout-position-top-zero uitk-layout-position-left-zero uitk-layout-position-relative"><figure class="uitk-image uitk-layout-position uitk-layout-position-zindex-layer2 uitk-image-fit-cover uitk-image-ratio-21-9 uitk-image-ratio"><span><span><div class="uitk-gallery-carousel"><h3 class="is-visually-hidden">Photo gallery for Best Western Plus Pepper Tree Inn</h3><div class="uitk-gallery-carousel-items ratio-21-9"><div aria-hidden="true" class="uitk-gallery-carousel-item uitk-gallery-carousel-item-prev"><figure class="uitk-image uitk-image-fit-cover uitk-image-ratio-21-9 uitk-image-ratio"><div class="uitk-image-placeholder"><img alt="Room" class="uitk-image-media" data-loaded="true" src="https://images.trvl-media.com/lodging/1000000/20000/13600/13530/f4da2557.jpg?impolicy=resizecrop&amp;rw=455&amp;ra=fit"/></div></figure></div><div aria-hidden="false" class="uitk-gallery-carousel-item uitk-gallery-carousel-item-current"><figure class="uitk-image uitk-image-fit-cover uitk-image-ratio-21-9 uitk-image-ratio"><div class="uitk-image-placeholder uitk-image-placeholder-image"><img alt="Exterior" class="uitk-image-media" fetchpriority="high" src="https://images.trvl-media.com/lodging/1000000/20000/13600/13530/3949e4b6.jpg?impolicy=resizecrop&amp;rw=455&amp;ra=fit"/></div><button aria-label="More information about Best Western Plus Pepper Tree Inn, opens in a new tab" class="uitk-image-link" data-testid="uitk-gallery-item-current-trigger" type="button"><span class="is-visually-hidden">Exterior</span></button></figure></div><div aria-hidden="true" class="uitk-gallery-carousel-item uitk-gallery-carousel-item-next"><figure class="uitk-image uitk-image-fit-cover uitk-image-ratio-21-9 uitk-image-ratio"><div class="uitk-image-placeholder"><img alt="Beach" class="uitk-image-media" data-loaded="true" src="https://images.trvl-media.com/lodging/1000000/20000/13600/13530/f37a22e3.jpg?impolicy=resizecrop&amp;rw=455&amp;ra=fit"/></div></figure></div><div aria-hidden="true" class="uitk-gallery-carousel-item uitk-gallery-carousel-item-queued"><figure class="uitk-image uitk-image-fit-cover uitk-image-ratio-21-9 uitk-image-ratio"><div class="uitk-image-placeholder"><img alt="Room" class="uitk-image-media" data-loaded="true" src="https://images.trvl-media.com/lodging/1000000/20000/13600/13530/94f81c27.jpg?impolicy=resizecrop&amp;rw=455&amp;ra=fit"/></div></figure></div></div><div class="uitk-gallery-carousel-paging-controls"><button class="uitk-button uitk-button-medium uitk-button-only-icon uitk-gallery-carousel-button-prev uitk-button-paging uitk-button-paging-overlay" theme="transparent-btn" type="button"><svg aria-label="Show previous image for Best Western Plus Pepper Tree Inn" class="uitk-icon uitk-icon-leading uitk-icon-directional" role="img" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><title id="prev-button-lodging-card-gallery-carousel-13530-1-title">Show previous image for Best Western Plus Pepper Tree Inn</title><path d="M15.41 7.41 14 6l-6 6 6 6 1.41-1.41L10.83 12l4.58-4.59z"></path></svg></button><button class="uitk-button uitk-button-medium uitk-button-only-icon uitk-gallery-carousel-button-next uitk-button-paging uitk-button-paging-overlay" theme="transparent-btn" type="button"><svg aria-label="Show next image for Best Western Plus Pepper Tree Inn" class="uitk-icon uitk-icon-leading uitk-icon-directional" role="img" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><title id="next-button-lodging-card-gallery-carousel-13530-1-title">Show next image for Best Western Plus Pepper Tree Inn</title><path d="M10 6 8.59 7.41 13.17 12l-4.58 4.59L10 18l6-6-6-6z"></path></svg></button></div></div></span></span></figure><div class="uitk-layout-position uitk-layout-position-top-zero uitk-layout-position-right-zero uitk-layout-position-zindex-layer2 uitk-layout-position-absolute"> <div data-stid="outlined-save-button" id="trip-save-item-ujs"><div class="favorite-button-wrapper"><button aria-label="Save Best Western Plus Pepper Tree Inn to a trip" class="favorite-button favorite-button-button-no-label" type="button"><svg aria-hidden="true" class="uitk-icon favorite-button-fill favorite-button-fill-default" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path clip-rule="evenodd" d="m12 22-8.44-8.69a5.55 5.55 0 0 1 0-7.72C4.53 4.59 5.9 4 7.28 4c1.4 0 2.75.59 3.72 1.59l1 1.02 1-1.02c.97-1 2.32-1.59 3.72-1.59 1.4 0 2.75.59 3.72 1.59a5.55 5.55 0 0 1 0 7.72L12 22Z" fill-rule="evenodd"></path></svg><svg aria-hidden="true" class="uitk-icon favorite-button-border favorite-button-border-default favorite-button-border-color-highlighed" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path clip-rule="evenodd" d="m12 22 8.44-8.69a5.55 5.55 0 0 0 0-7.72A5.24 5.24 0 0 0 16.72 4 5.22 5.22 0 0 0 13 5.59L12 6.6l-1-1.02a5.2 5.2 0 0 0-7.44 0 5.55 5.55 0 0 0 0 7.72L12 22Zm0-2.87-7-7.21a3.55 3.55 0 0 1 0-4.94C5.6 6.36 6.44 6 7.28 6c.84 0 1.69.36 2.3.98L12 9.48l2.43-2.5c.6-.62 1.45-.98 2.29-.98.84 0 1.68.36 2.28.98a3.55 3.55 0 0 1 0 4.94l-7 7.2Z" fill-rule="evenodd" opacity=".9"></path></svg></button></div></div> </div></div><div class="uitk-card-content-section uitk-card-content-section-padded uitk-layout-grid-item uitk-layout-grid-item-has-column-start-by-medium" style="--uitk-layoutgrid-column-start-medium:span 2"><div class="uitk-layout-flex uitk-layout-flex-block-size-full-size uitk-layout-flex-flex-direction-column uitk-layout-flex-justify-content-space-between" style="min-height:143px"><div class="uitk-spacing uitk-spacing-padding-blockend-three uitk-layout-flex-item"><div class="uitk-layout-flex uitk-layout-flex-justify-content-space-between uitk-layout-flex-gap-two"><div class="uitk-layout-grid uitk-layout-grid-has-auto-columns uitk-layout-grid-has-rows uitk-layout-grid-display-grid uitk-layout-flex-item" style="--uitk-layoutgrid-auto-columns:minmax(var(--uitk-layoutgrid-egds-size__0x), 1fr);--uitk-layoutgrid-rows:min-content"><h3 class="uitk-heading uitk-heading-5 overflow-wrap uitk-layout-grid-item uitk-layout-grid-item-has-row-start" style="--uitk-layoutgrid-row-start:span 1">Best Western Plus Pepper Tree Inn</h3></div></div><div aria-hidden="false" class="uitk-text uitk-text-spacing-half truncate-lines-2 uitk-type-300 uitk-text-default-theme">Santa Barbara</div><div class="uitk-layout-flex uitk-layout-flex-flex-wrap-wrap uitk-spacing uitk-spacing-margin-blockstart-one"><div class="uitk-layout-flex uitk-layout-flex-align-items-center uitk-layout-flex-gap-two uitk-spacing uitk-spacing-padding-inlineend-three uitk-spacing-padding-block-one"><svg aria-hidden="true" class="uitk-icon uitk-icon-small" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M9.82 11.64h.01a4.15 4.15 0 0 1 4.36 0h.01c.76.46 1.54.47 2.29 0l.41-.23L10.48 5C8.93 3.45 7.5 2.99 5 3v2.5c1.82-.01 2.89.39 4 1.5l1 1-3.25 3.25c.27.1.52.25.77.39.75.47 1.55.47 2.3 0z"></path><path clip-rule="evenodd" d="M21.98 16.5c-1.1 0-1.71-.37-2.16-.64h-.01a2.08 2.08 0 0 0-2.29 0 4.13 4.13 0 0 1-4.36 0h-.01a2.08 2.08 0 0 0-2.29 0 4.13 4.13 0 0 1-4.36 0h-.01a2.08 2.08 0 0 0-2.29 0l-.03.02c-.47.27-1.08.62-2.17.62v-2c.56 0 .78-.13 1.15-.36a4.13 4.13 0 0 1 4.36 0h.01c.76.46 1.54.47 2.29 0a4.13 4.13 0 0 1 4.36 0h.01c.76.46 1.54.47 2.29 0a4.13 4.13 0 0 1 4.36 0h.01c.36.22.6.36 1.14.36v2z" fill-rule="evenodd"></path><path d="M19.82 20.36c.45.27 1.07.64 2.18.64v-2a1.8 1.8 0 0 1-1.15-.36 4.13 4.13 0 0 0-4.36 0c-.75.47-1.53.46-2.29 0h-.01a4.15 4.15 0 0 0-4.36 0h-.01c-.75.47-1.55.47-2.3 0a4.15 4.15 0 0 0-4.36 0h-.01A1.8 1.8 0 0 1 2 19v2c1.1 0 1.72-.36 2.18-.63l.01-.01a2.07 2.07 0 0 1 2.3 0c1.39.83 2.97.82 4.36 0h.01a2.08 2.08 0 0 1 2.29 0h.01c1.38.83 2.95.83 4.34.01l.02-.01a2.08 2.08 0 0 1 2.29 0h.01zM19 5.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0z"></path></svg><div class="uitk-text truncate-lines-2 uitk-type-200 uitk-text-default-theme">Pool</div></div></div></div><div class="uitk-layout-grid uitk-layout-grid-has-auto-columns uitk-layout-grid-has-columns uitk-layout-grid-has-columns-by-medium uitk-layout-grid-has-columns-by-large uitk-layout-grid-has-space uitk-layout-grid-display-grid uitk-layout-flex-item" style="--uitk-layoutgrid-auto-columns:minmax(var(--uitk-layoutgrid-egds-size__0x), 1fr);--uitk-layoutgrid-columns:1fr 2fr 2fr;--uitk-layoutgrid-columns-medium:1fr 2fr 2fr;--uitk-layoutgrid-columns-large:1fr max-content max-content;--uitk-layoutgrid-column-gap:var(--uitk-layoutgrid-space-one);--uitk-layoutgrid-row-gap:var(--uitk-layoutgrid-space-one)"><div class="uitk-layout-grid-item uitk-layout-grid-item-align-self-end uitk-layout-grid-item-has-column-start" style="--uitk-layoutgrid-column-start:span 2"><div class="uitk-layout-flex uitk-layout-flex-flex-direction-column uitk-layout-flex-gap-three uitk-spacing uitk-spacing-margin-blockstart-"><div><div class="uitk-layout-flex uitk-layout-flex-align-items-center uitk-layout-flex-gap-one"><div class="uitk-layout-flex uitk-layout-flex-align-items-center"><span class="uitk-badge uitk-badge-base-large uitk-badge-base-has-text uitk-badge-positive"><span aria-hidden="true" class="uitk-badge-base-text">8.2</span><span class="is-visually-hidden">8.2 out of 10</span></span></div><div class="uitk-layout-flex uitk-layout-flex-flex-direction-column uitk-layout-flex-item"><div class="uitk-layout-flex uitk-layout-flex-align-items-center uitk-layout-flex-gap-one"><span aria-hidden="true" class="uitk-text uitk-type-300 uitk-type-medium uitk-text-emphasis-theme">Very Good</span><span class="is-visually-hidden">very good</span></div><div class="uitk-layout-flex uitk-layout-flex-align-items-center uitk-layout-flex-gap-one"><span aria-hidden="true" class="uitk-text uitk-type-200 uitk-type-regular uitk-text-default-theme">1,007 reviews</span><span class="is-visually-hidden">(1,007 reviews)</span></div></div></div></div></div></div><div class="uitk-layout-flex uitk-layout-flex-flex-direction-column uitk-layout-grid-item uitk-layout-grid-item-align-self-end uitk-layout-grid-item-has-column-start uitk-layout-grid-item-justify-self-end" style="--uitk-layoutgrid-column-start:span 1"><span class="uitk-badge uitk-badge-large uitk-badge-deal-generic uitk-badge-has-text uitk-layout-flex-item-align-self-flex-end uitk-layout-flex-item"><span aria-hidden="false" class="uitk-badge-text">We have 2 left at</span></span><div class="uitk-layout-flex uitk-layout-flex-flex-direction-column" data-test-id="price-summary"><div><div class="uitk-layout-flex uitk-layout-flex-align-items-center uitk-layout-flex-flex-direction-row uitk-layout-flex-justify-content-flex-end uitk-layout-flex-gap-one uitk-layout-flex-flex-wrap-wrap" data-test-id="price-summary-message-line"><div class="uitk-spacing uitk-spacing-padding-block-half"><div class="uitk-text uitk-type-300 uitk-text-default-theme is-visually-hidden">The price is $294</div><span aria-hidden="true"><div class="uitk-text uitk-type-500 uitk-type-medium uitk-text-emphasis-theme">$294</div></span></div></div><div class="uitk-layout-flex uitk-layout-flex-align-items-center uitk-layout-flex-flex-direction-row uitk-layout-flex-justify-content-flex-end uitk-layout-flex-gap-one uitk-layout-flex-flex-wrap-wrap" data-test-id="price-summary-message-line"><div class="uitk-text uitk-type-end uitk-type-200 uitk-text-default-theme">$672 total</div></div><div class="uitk-layout-flex uitk-layout-flex-align-items-center uitk-layout-flex-flex-direction-row uitk-layout-flex-justify-content-flex-end uitk-layout-flex-gap-one uitk-layout-flex-flex-wrap-wrap" data-test-id="price-summary-message-line"><div class="uitk-text uitk-type-end uitk-type-200 uitk-text-default-theme">includes taxes &amp; fees</div></div></div></div></div></div></div></div></div><a class="uitk-card-link" data-stid="open-hotel-information" href="/Santa-Barbara-Hotels-Best-Western-Plus-Pepper-Tree-Inn.h13530.Hotel-Information?chkin=2024-06-28&amp;chkout=2024-06-30&amp;x_pwa=1&amp;rfrr=HSR&amp;pwa_ts=1719094848651&amp;referrerUrl=aHR0cHM6Ly93d3cuZXhwZWRpYS5jb20vSG90ZWwtU2VhcmNo&amp;useRewards=false&amp;rm1=a2&amp;regionId=602277&amp;destination=Santa+Barbara%2C+California%2C+United+States+of+America&amp;destType=MARKET&amp;neighborhoodId=553248635976471154&amp;latLong=34.423549%2C-119.703684&amp;lodging=HOTEL&amp;sort=RECOMMENDED&amp;top_dp=294&amp;top_cur=USD&amp;userIntent=&amp;selectedRoomType=324481198&amp;selectedRatePlan=394762239&amp;searchId=5469c411-d314-4164-9f49-f3609bba284e&amp;propertyName=Best+Western+Plus+Pepper+Tree+Inn" rel="noopener" target="_blank"><span class="is-visually-hidden">More information about Best Western Plus Pepper Tree Inn, opens in a new tab</span></a></div></div>,

In [91]:
data_temp = []
start_date = '2024-09-01'
end_date = '2024-12-31'
date_range_list = pd.date_range(start = start_date, end = end_date)

options = uc.ChromeOptions()# have to use undetected driver to load the expedia page. 
prefs = {"download.default_directory": "/Users/bowiechuang/Downloads/"}
options.add_experimental_option("prefs", prefs) 
options.add_argument("--disable-gpu") #to disabled gpu because expedia page is written by javascript 
#options.add_argument("--headless")
#options.headless = True
service = ChromeService("/Users/bowiechuang/Downloads/chromedriver-mac-x64/chromedriver")
driver = uc.Chrome(options = options)

for i in range(len(date_range_list)):
    try:
        url = f"https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1={date_range_list.date[i]}&startDate={date_range_list.date[i]}&d2={date_range_list.date[i+2]}&endDate={date_range_list.date[i+2]}&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED"
        driver.get(url)
        #time.sleep(5)

        WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CLASS_NAME, "uitk-button.uitk-button-medium.uitk-button-has-text.uitk-button-secondary"))).click()

        last_height = driver.execute_script("return document.body.scrollHeight")
        while True:
            #scroll down to bottom
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(3)
            new_height = driver.execute_script("return document.body.scrollHeight")
            if new_height== last_height:
                break
            last_height = new_height

        time.sleep(5)

        content = driver.page_source
        soup = BeautifulSoup(content, 'html.parser')
        # Find the elements containing hotel information
        hotel_elements = soup.find_all('div', class_='uitk-card')

        for hotel in hotel_elements:
            # Extract hotel# name
            hotel_name_tag = hotel.find('h3', class_='uitk-heading-5')
            hotel_name = hotel_name_tag.text.strip() if hotel_name_tag else 'No name'
            
            # Extract hotel price
            hotel_price_tag = hotel.find('div', class_='uitk-text-emphasis-theme')
            hotel_price = hotel_price_tag.text.strip() if hotel_price_tag else 'No price'

            # Extract hotel city location
            hotel_city_tag = hotel.find("div", class_ = "uitk-text-spacing-half")
            hotel_city = hotel_city_tag.text.strip() if hotel_city_tag else 'No name'

            hotel_details = [tag.get_text(strip = True) for tag in hotel.findAll("div", class_ = "uitk-type-200")]
            # Extract rating
            rating_tag = hotel.find("span", class_="uitk-badge-base-text")
            rating = rating_tag.text.strip() if rating_tag else "No rating"

            review_tag = hotel.find("span", class_="uitk-text uitk-type-300 uitk-type-medium uitk-text-emphasis-theme")
            review = review_tag.text.strip() if review_tag else "No review"

            number_review_tag = hotel.find("span", class_="uitk-text uitk-type-200 uitk-type-regular uitk-text-default-theme")
            number_review = number_review_tag.text.strip() if number_review_tag else "No Number Review"


            

            # Append the data to the list
            data_temp.append({
                'hotel_name': hotel_name,
                'hotel_price': hotel_price,
                'hotel_city': hotel_city,
                'hotel_details' : hotel_details,
                'hotel_rating' : rating,
                'hotel_review' : review,
                'Number_review' : number_review,
                'start_date': date_range_list.date[i], 
                'end_date': date_range_list.date[i+2]
            })

        
    except:
        break
driver.quit()

In [92]:
df_temp = pd.DataFrame(data_temp)
#df_temp = df_temp[df_temp['hotel_name'] != 'No name']
df_temp

,hotel_name,hotel_price,hotel_city,hotel_details,hotel_rating,hotel_review,Number_review,start_date,end_date
0,No name,No price,No name,[],No rating,No review,No Number Review,2024-09-01,2024-09-03
1,No name,No price,No name,[],No rating,No review,No Number Review,2024-09-01,2024-09-03
2,No name,No price,No name,[],No rating,No review,No Number Review,2024-09-01,2024-09-03
3,"Drift Santa Barbara, a Member of Design Hotels",$757,Santa Barbara,"[New Boutique Hotel On State Street, Your coas...",Ad,Very Good,300 reviews,2024-09-01,2024-09-03
4,"The Leta Santa Barbara Goleta, Tapestry Collec...",$509,Goleta,"[Pool, A Bohemian Oasis near Santa Barbara, Re...",Ad,Excellent,557 reviews,2024-09-01,2024-09-03
...,...,...,...,...,...,...,...,...,...
3860,Hotel Santa Barbara,$750,Santa Barbara,"[includes taxes & fees, $329 per night]",8.8,Excellent,"1,001 reviews",2024-12-29,2024-12-31
3861,"Brisas del Mar, Inn at the Beach",$797,Santa Barbara,"[Breakfast included, Pool, Hot tub, includes t...",9.6,Exceptional,"1,179 reviews",2024-12-29,2024-12-31
3862,Lavender Inn by the Sea,$751,Santa Barbara,"[Breakfast included, Pool, includes taxes & fe...",9.4,Exceptional,"1,287 reviews",2024-12-29,2024-12-31
3863,Best Western Plus Santa Barbara,$455,Santa Barbara,"[Pool, Hot tub, includes taxes & fees, $199 pe...",8.8,Excellent,"1,003 reviews",2024-12-29,2024-12-31
3864,Harbor View Inn,$766,Santa Barbara,"[Pool, Hot tub, includes taxes & fees, $336 pe...",9.2,Wonderful,"1,002 reviews",2024-12-29,2024-12-31

In [55]:
df = pd.DataFrame(data)
df
# Save it here for now, will remove it later.

,hotel_name,hotel_price,hotel_city,hotel_details,start_date,end_date
0,No name,No price,No name,[],2024-09-01,2024-09-03
1,No name,No price,No name,[],2024-09-01,2024-09-03
2,No name,No price,No name,[],2024-09-01,2024-09-03
3,Hotel Milo Santa Barbara,$825,Santa Barbara,"[Pool, Hot tub, for 2 nights, includes taxes &...",2024-09-01,2024-09-03
4,Lavender Inn by the Sea,$698,Santa Barbara,"[Breakfast included, Pool, for 2 nights, inclu...",2024-09-01,2024-09-03
...,...,...,...,...,...,...
1068,"Motel 6 Santa Barbara, CA - Beach",$512,East Beach,"[Pool, for 2 nights, includes taxes & fees, $2...",2024-09-11,2024-09-13
1069,Hotel Corque,$401,Solvang,"[Pool, Hot tub, for 2 nights, includes taxes &...",2024-09-11,2024-09-13
1070,Wine Valley Inn,$396,Solvang,"[Breakfast included, for 2 nights, includes ta...",2024-09-11,2024-09-13
1071,"West Beach Inn, a Coast Hotel",$762,Santa Barbara,"[Breakfast included, Pool, for 2 nights, inclu...",2024-09-11,2024-09-13
1072,Avania Inn of Santa Barbara,$744,Santa Barbara,"[Breakfast included, Pool, Hot tub, for 2 nigh...",2024-09-11,2024-09-13

In [82]:
df_filter = df[df['hotel_name'] != 'No name']
breakfast = [None] * len(df_filter)
pool = [None] * len(df_filter)
hot_tub = [None] * len(df_filter)
per_night_fee = [None] * len(df_filter)
for index, hotel in enumerate(df_filter['hotel_details']):
    if "Breakfast included" in hotel:
        breakfast[index] = "Breakfast"
    if "Pool" in hotel:
        pool[index] = "Pool"
    if "Hot tub" in hotel:
        hot_tub[index] = "Hot tub"
    if hotel[-1] is not None:
        per_night_fee[index] = hotel[-1]

In [99]:
df_temp = df_temp[df_temp['hotel_name'] != 'No name']
breakfast = [None] * len(df_temp)
pool = [None] * len(df_temp)
hot_tub = [None] * len(df_temp)
per_night_fee = [None] * len(df_temp)
for index, hotel in enumerate(df_temp['hotel_details']):
    if "Breakfast included" in hotel:
        breakfast[index] = "Breakfast"
    if "Pool" in hotel:
        pool[index] = "Pool"
    if "Hot tub" in hotel:
        hot_tub[index] = "Hot tub"
    if len(hotel) > 0 and hotel[-1] is not None:
        per_night_fee[index] = hotel[-1]
    else:
        per_night_fee[index] = 'No Data'
df_temp['Breakfast'] = breakfast
df_temp['Pool'] = pool
df_temp['Hottub'] = hot_tub
df_temp['Per_Night_Fee'] = per_night_fee
#df_filter = df_filter.drop("hotel_details", axis =1)

In [100]:
df_temp

,hotel_name,hotel_price,hotel_city,hotel_details,hotel_rating,hotel_review,Number_review,start_date,end_date,Breakfast,Pool,Hottub,Per_Night_Fee
3,"Drift Santa Barbara, a Member of Design Hotels",$757,Santa Barbara,"[New Boutique Hotel On State Street, Your coas...",Ad,Very Good,300 reviews,2024-09-01,2024-09-03,None,None,None,$332 per night
4,"The Leta Santa Barbara Goleta, Tapestry Collec...",$509,Goleta,"[Pool, A Bohemian Oasis near Santa Barbara, Re...",Ad,Excellent,557 reviews,2024-09-01,2024-09-03,None,Pool,None,$219 per night
5,"Brisas del Mar, Inn at the Beach",$759,Santa Barbara,"[Breakfast included, Pool, Hot tub, includes t...",9.6,Exceptional,"1,179 reviews",2024-09-01,2024-09-03,Breakfast,Pool,Hot tub,$333 per night
6,Lavender Inn by the Sea,$698,Santa Barbara,"[Breakfast included, Pool, includes taxes & fe...",9.4,Exceptional,"1,287 reviews",2024-09-01,2024-09-03,Breakfast,Pool,None,$306 per night
7,"West Beach Inn, a Coast Hotel",$762,Santa Barbara,"[Breakfast included, Pool, includes taxes & fe...",9.4,Exceptional,"1,003 reviews",2024-09-01,2024-09-03,Breakfast,Pool,None,$334 per night
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3860,Hotel Santa Barbara,$750,Santa Barbara,"[includes taxes & fees, $329 per night]",8.8,Excellent,"1,001 reviews",2024-12-29,2024-12-31,None,None,None,$329 per night
3861,"Brisas del Mar, Inn at the Beach",$797,Santa Barbara,"[Breakfast included, Pool, Hot tub, includes t...",9.6,Exceptional,"1,179 reviews",2024-12-29,2024-12-31,Breakfast,Pool,Hot tub,$349 per night
3862,Lavender Inn by the Sea,$751,Santa Barbara,"[Breakfast included, Pool, includes taxes & fe...",9.4,Exceptional,"1,287 reviews",2024-12-29,2024-12-31,Breakfast,Pool,None,$329 per night
3863,Best Western Plus Santa Barbara,$455,Santa Barbara,"[Pool, Hot tub, includes taxes & fees, $199 pe...",8.8,Excellent,"1,003 reviews",2024-12-29,2024-12-31,None,Pool,Hot tub,$199 per night
3864,Harbor View Inn,$766,Santa Barbara,"[Pool, Hot tub, includes taxes & fees, $336 pe...",9.2,Wonderful,"1,002 reviews",2024-12-29,2024-12-31,None,Pool,Hot tub,$336 per night

In [101]:
df_temp.to_excel("/Users/bowiechuang/Downloads/expedia_scrape_test_Sep.xlsx")

In [104]:
data_temp4 = []
start_date = '2025-03-12'
end_date = '2025-08-31'
date_range_list = pd.date_range(start = start_date, end = end_date)

options = uc.ChromeOptions()# have to use undetected driver to load the expedia page. 
prefs = {"download.default_directory": "/Users/bowiechuang/Downloads/"}
options.add_experimental_option("prefs", prefs) 
options.add_argument("--disable-gpu") #to disabled gpu because expedia page is written by javascript 
#options.add_argument("--headless")
#options.headless = True
service = ChromeService("/Users/bowiechuang/Downloads/chromedriver-mac-x64/chromedriver")
driver = uc.Chrome(options = options)

for i in range(len(date_range_list)):
    try:
        url = f"https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1={date_range_list.date[i]}&startDate={date_range_list.date[i]}&d2={date_range_list.date[i+2]}&endDate={date_range_list.date[i+2]}&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED"
        driver.get(url)
        #time.sleep(5)

        WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CLASS_NAME, "uitk-button.uitk-button-medium.uitk-button-has-text.uitk-button-secondary"))).click()

        last_height = driver.execute_script("return document.body.scrollHeight")
        while True:
            #scroll down to bottom
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(5)
            new_height = driver.execute_script("return document.body.scrollHeight")
            if new_height== last_height:
                break
            last_height = new_height

        time.sleep(8)

        content = driver.page_source
        soup = BeautifulSoup(content, 'html.parser')
        # Find the elements containing hotel information
        hotel_elements = soup.find_all('div', class_='uitk-card')

        for hotel in hotel_elements:
            # Extract hotel# name
            hotel_name_tag = hotel.find('h3', class_='uitk-heading-5')
            hotel_name = hotel_name_tag.text.strip() if hotel_name_tag else 'No name'
            
            # Extract hotel price
            hotel_price_tag = hotel.find('div', class_='uitk-text-emphasis-theme')
            hotel_price = hotel_price_tag.text.strip() if hotel_price_tag else 'No price'

            # Extract hotel city location
            hotel_city_tag = hotel.find("div", class_ = "uitk-text-spacing-half")
            hotel_city = hotel_city_tag.text.strip() if hotel_city_tag else 'No name'

            hotel_details = [tag.get_text(strip = True) for tag in hotel.findAll("div", class_ = "uitk-type-200")]
            # Extract rating
            rating_tag = hotel.find("span", class_="uitk-badge-base-text")
            rating = rating_tag.text.strip() if rating_tag else "No rating"

            review_tag = hotel.find("span", class_="uitk-text uitk-type-300 uitk-type-medium uitk-text-emphasis-theme")
            review = review_tag.text.strip() if review_tag else "No review"

            number_review_tag = hotel.find("span", class_="uitk-text uitk-type-200 uitk-type-regular uitk-text-default-theme")
            number_review = number_review_tag.text.strip() if number_review_tag else "No Number Review"


            

            # Append the data to the list
            data_temp4.append({
                'hotel_name': hotel_name,
                'hotel_price': hotel_price,
                'hotel_city': hotel_city,
                'hotel_details' : hotel_details,
                'hotel_rating' : rating,
                'hotel_review' : review,
                'Number_review' : number_review,
                'start_date': date_range_list.date[i], 
                'end_date': date_range_list.date[i+2]
            })

        
    except:
        break
driver.quit()

In [103]:
df2 = pd.DataFrame(data_temp2)
df2

,hotel_name,hotel_price,hotel_city,hotel_details,hotel_rating,hotel_review,Number_review,start_date,end_date
0,No name,No price,No name,[],No rating,No review,No Number Review,2024-12-30,2025-01-01
1,No name,No price,No name,[],No rating,No review,No Number Review,2024-12-30,2025-01-01
2,No name,No price,No name,[],No rating,No review,No Number Review,2024-12-30,2025-01-01
3,Hotel Milo Santa Barbara,$648,Santa Barbara,"[Pool, Hot tub, Coastal Retreat in Santa Barba...",Ad,Very Good,"1,154 reviews",2024-12-30,2025-01-01
4,Hotel Milo Santa Barbara,$648,Santa Barbara,"[Pool, Hot tub, includes taxes & fees, $284 pe...",8.2,Very Good,"1,154 reviews",2024-12-30,2025-01-01
...,...,...,...,...,...,...,...,...,...
1036,"Brisas del Mar, Inn at the Beach",$747,Santa Barbara,"[Breakfast included, Pool, Hot tub, includes t...",9.6,Exceptional,"1,179 reviews",2025-01-29,2025-01-31
1037,The Franciscan Hotel,$477,Santa Barbara,"[Pool, Hot tub, includes taxes & fees, $209 pe...",9.4,Exceptional,"1,011 reviews",2025-01-29,2025-01-31
1038,La Playa Inn,$599,Santa Barbara,"[includes taxes & fees, $263 per night]",9.6,Exceptional,905 reviews,2025-01-29,2025-01-31
1039,Hyatt Place Santa Barbara,$452,Santa Barbara,"[Breakfast included, includes taxes & fees, $1...",8.2,Very Good,"1,007 reviews",2025-01-29,2025-01-31
1040,Hotel Santa Barbara,$750,Santa Barbara,"[includes taxes & fees, $329 per night]",8.8,Excellent,"1,001 reviews",2025-01-29,2025-01-31

In [108]:
data_temp4 = []
start_date = '2025-03-12'
end_date = '2025-08-31'
date_range_list = pd.date_range(start = start_date, end = end_date)

options = uc.ChromeOptions()# have to use undetected driver to load the expedia page. 
prefs = {"download.default_directory": "/Users/bowiechuang/Downloads/"}
options.add_experimental_option("prefs", prefs) 
options.add_argument("--disable-gpu") #to disabled gpu because expedia page is written by javascript 
#options.add_argument("--headless")
#options.headless = True
service = ChromeService("/Users/bowiechuang/Downloads/chromedriver-mac-x64/chromedriver")
driver = uc.Chrome(options = options)

for i in range(len(date_range_list)):
    try:
        url = f"https://www.expedia.com/Hotel-Search?destination=Santa%20Barbara%2C%20California%2C%20United%20States%20of%20America&regionId=602277&flexibility=0_DAY&d1={date_range_list.date[i]}&startDate={date_range_list.date[i]}&d2={date_range_list.date[i+2]}&endDate={date_range_list.date[i+2]}&adults=2&rooms=1&theme=&userIntent=&semdtl=&useRewards=false&sort=RECOMMENDED"
        driver.get(url)
        #time.sleep(5)

        WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CLASS_NAME, "uitk-button.uitk-button-medium.uitk-button-has-text.uitk-button-secondary"))).click()

        last_height = driver.execute_script("return document.body.scrollHeight")
        while True:
            #scroll down to bottom
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(5)
            new_height = driver.execute_script("return document.body.scrollHeight")
            if new_height== last_height:
                break
            last_height = new_height

        time.sleep(8)

        content = driver.page_source
        soup = BeautifulSoup(content, 'html.parser')
        # Find the elements containing hotel information
        hotel_elements = soup.find_all('div', class_='uitk-card')

        for hotel in hotel_elements:
            # Extract hotel# name
            hotel_name_tag = hotel.find('h3', class_='uitk-heading-5')
            hotel_name = hotel_name_tag.text.strip() if hotel_name_tag else 'No name'
            
            # Extract hotel price
            hotel_price_tag = hotel.find('div', class_='uitk-text-emphasis-theme')
            hotel_price = hotel_price_tag.text.strip() if hotel_price_tag else 'No price'

            # Extract hotel city location
            hotel_city_tag = hotel.find("div", class_ = "uitk-text-spacing-half")
            hotel_city = hotel_city_tag.text.strip() if hotel_city_tag else 'No name'

            hotel_details = [tag.get_text(strip = True) for tag in hotel.findAll("div", class_ = "uitk-type-200")]
            # Extract rating
            rating_tag = hotel.find("span", class_="uitk-badge-base-text")
            rating = rating_tag.text.strip() if rating_tag else "No rating"

            review_tag = hotel.find("span", class_="uitk-text uitk-type-300 uitk-type-medium uitk-text-emphasis-theme")
            review = review_tag.text.strip() if review_tag else "No review"

            number_review_tag = hotel.find("span", class_="uitk-text uitk-type-200 uitk-type-regular uitk-text-default-theme")
            number_review = number_review_tag.text.strip() if number_review_tag else "No Number Review"


            

            # Append the data to the list
            data_temp4.append({
                'hotel_name': hotel_name,
                'hotel_price': hotel_price,
                'hotel_city': hotel_city,
                'hotel_details' : hotel_details,
                'hotel_rating' : rating,
                'hotel_review' : review,
                'Number_review' : number_review,
                'start_date': date_range_list.date[i], 
                'end_date': date_range_list.date[i+2]
            })

        
    except:
        break
driver.quit()

In [109]:
df4 = pd.DataFrame(data_temp4)
df4

,hotel_name,hotel_price,hotel_city,hotel_details,hotel_rating,hotel_review,Number_review,start_date,end_date
0,No name,No price,No name,[],No rating,No review,No Number Review,2025-03-12,2025-03-14
1,No name,No price,No name,[],No rating,No review,No Number Review,2025-03-12,2025-03-14
2,"Drift Santa Barbara, a Member of Design Hotels",$584,Santa Barbara,"[New Boutique Hotel On State Street, Your coas...",Ad,Very Good,300 reviews,2025-03-12,2025-03-14
3,Hotel Milo Santa Barbara,$585,Santa Barbara,"[Pool, Hot tub, Coastal Retreat in Santa Barba...",Ad,Very Good,"1,156 reviews",2025-03-12,2025-03-14
4,Hotel Milo Santa Barbara,$585,Santa Barbara,"[Pool, Hot tub, includes taxes & fees, $256 pe...",8.2,Very Good,"1,156 reviews",2025-03-12,2025-03-14
...,...,...,...,...,...,...,...,...,...
4007,Fabulous Studio/Suite With Private Entrance,$408,Entire apartment,"[Kitchen, Washer and dryer, includes taxes & f...",9.6,Exceptional,25 reviews,2025-08-29,2025-08-31
4008,Agave Inn,$775,Santa Barbara,"[includes taxes & fees, $340 per night]",8.8,Excellent,636 reviews,2025-08-29,2025-08-31
4009,The Eagle Inn,"$1,045",Santa Barbara,"[Breakfast included, includes taxes & fees, $4...",9.4,Exceptional,"1,002 reviews",2025-08-29,2025-08-31
4010,"Ocean, Sunset, Mountain Views, Private Deck: V...",$910,Entire apartment,"[Kitchen, Washer and dryer, includes taxes & f...",10,Exceptional,104 reviews,2025-08-29,2025-08-31
4011,Ojai Retreat & Inn,$348,Ojai,"[Breakfast included, includes taxes & fees, $1...",9.4,Exceptional,272 reviews,2025-08-29,2025-08-31

In [111]:
df_temp2 = pd.concat([df2, df3, df4])
df_temp2

,hotel_name,hotel_price,hotel_city,hotel_details,hotel_rating,hotel_review,Number_review,start_date,end_date
0,No name,No price,No name,[],No rating,No review,No Number Review,2024-12-30,2025-01-01
1,No name,No price,No name,[],No rating,No review,No Number Review,2024-12-30,2025-01-01
2,No name,No price,No name,[],No rating,No review,No Number Review,2024-12-30,2025-01-01
3,Hotel Milo Santa Barbara,$648,Santa Barbara,"[Pool, Hot tub, Coastal Retreat in Santa Barba...",Ad,Very Good,"1,154 reviews",2024-12-30,2025-01-01
4,Hotel Milo Santa Barbara,$648,Santa Barbara,"[Pool, Hot tub, includes taxes & fees, $284 pe...",8.2,Very Good,"1,154 reviews",2024-12-30,2025-01-01
...,...,...,...,...,...,...,...,...,...
4007,Fabulous Studio/Suite With Private Entrance,$408,Entire apartment,"[Kitchen, Washer and dryer, includes taxes & f...",9.6,Exceptional,25 reviews,2025-08-29,2025-08-31
4008,Agave Inn,$775,Santa Barbara,"[includes taxes & fees, $340 per night]",8.8,Excellent,636 reviews,2025-08-29,2025-08-31
4009,The Eagle Inn,"$1,045",Santa Barbara,"[Breakfast included, includes taxes & fees, $4...",9.4,Exceptional,"1,002 reviews",2025-08-29,2025-08-31
4010,"Ocean, Sunset, Mountain Views, Private Deck: V...",$910,Entire apartment,"[Kitchen, Washer and dryer, includes taxes & f...",10,Exceptional,104 reviews,2025-08-29,2025-08-31
4011,Ojai Retreat & Inn,$348,Ojai,"[Breakfast included, includes taxes & fees, $1...",9.4,Exceptional,272 reviews,2025-08-29,2025-08-31

In [112]:
df_temp2 = df_temp2[df_temp2['hotel_name'] != 'No name']
breakfast = [None] * len(df_temp2)
pool = [None] * len(df_temp2)
hot_tub = [None] * len(df_temp2)
per_night_fee = [None] * len(df_temp2)
for index, hotel in enumerate(df_temp2['hotel_details']):
    if "Breakfast included" in hotel:
        breakfast[index] = "Breakfast"
    if "Pool" in hotel:
        pool[index] = "Pool"
    if "Hot tub" in hotel:
        hot_tub[index] = "Hot tub"
    if len(hotel) > 0 and hotel[-1] is not None:
        per_night_fee[index] = hotel[-1]
    else:
        per_night_fee[index] = 'No Data'
df_temp2['Breakfast'] = breakfast
df_temp2['Pool'] = pool
df_temp2['Hottub'] = hot_tub
df_temp2['Per_Night_Fee'] = per_night_fee
#df_filter = df_filter.drop("hotel_details", axis =1)

/var/folders/hk/1l4v0gdd41z7xrwc5_b0pcmm0000gn/T/ipykernel_30898/3458381498.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp2['Breakfast'] = breakfast
/var/folders/hk/1l4v0gdd41z7xrwc5_b0pcmm0000gn/T/ipykernel_30898/3458381498.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp2['Pool'] = pool
/var/folders/hk/1l4v0gdd41z7xrwc5_b0pcmm0000gn/T/ipykernel_30898/3458381498.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp2['Hottub'] = hot_tub
/var/folders/hk/1l4v0gdd41z7xrwc5_b0pcmm0000gn/T/ipykernel_30898/3458381498.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp2['Per_Night_Fee'] = per_night_fee

In [121]:
df = pd.concat([df_temp, df_temp2])
kitchen = [None] * len(df)
w_d = [None] * len(df)
for index, hotel in enumerate(df['hotel_details']):
    if "Kitchen" in hotel:
        kitchen[index] = "Kitchen"
    if "Washer and dryer" in hotel:
        w_d[index] = "Washer and dryer"
df['Kitchen'] = kitchen
df['Washer_Dryer'] = w_d
df = df.reset_index(drop = True)

In [123]:
df.to_excel("/Users/bowiechuang/Downloads/Expedia_hotel_dataset.xlsx")